<?xml version="1.0" encoding="utf-8"?><Database Name="DB_Coffee" Class="DBC_CoffeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TRUNGLOC\SQLEXPRESS;Initial Catalog=DB_Coffee;Persist Security Info=True;User ID=sa" SettingsObjectName="CoffeeLibrary.Properties.Settings" SettingsPropertyName="DB_CoffeeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="account_user_group_user" Member="user_group_users" ThisKey="ID" OtherKey="ID_ACCOUNT" Type="user_group_user" />
      <Association Name="account_profile" Member="profiles" ThisKey="ID" OtherKey="ID_ACCOUNT" Type="profile" />
      <Association Name="account_receipt" Member="receipts" ThisKey="ID" OtherKey="ID_ACCOUNT_STAFF" Type="receipt" />
      <Association Name="account_receipt1" Member="receipts1" ThisKey="ID" OtherKey="ID_ACCOUNT_CUSTOMER" Type="receipt" />
      <Association Name="account_receipt_import" Member="receipt_imports" ThisKey="ID" OtherKey="ID_ACCOUNT" Type="receipt_import" />
      <Association Name="account_thuchi" Member="thuchis" ThisKey="ID" OtherKey="ID_ACCOUNT" Type="thuchi" />
      <Association Name="account_timekeeping" Member="timekeepings" ThisKey="ID" OtherKey="ID_ACCOUNT" Type="timekeeping" />
    </Type>
  </Table>
  <Table Name="dbo.user_group_user" Member="user_group_users">
    <Type Name="user_group_user">
      <Column Name="ID_ACCOUNT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_GROUP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="account_user_group_user" Member="account" ThisKey="ID_ACCOUNT" OtherKey="ID" Type="account" IsForeignKey="true" />
      <Association Name="group_user_user_group_user" Member="group_user" ThisKey="ID_GROUP" OtherKey="ID" Type="group_user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.area" Member="areas">
    <Type Name="area">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_AREA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="area_table" Member="tables" ThisKey="ID" OtherKey="ID_AREA" Type="table" />
    </Type>
  </Table>
  <Table Name="dbo.[convert]" Member="converts">
    <Type Name="convert">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_UNIT_BEFORE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUMBER_BEFORE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NAME_UNIT_AFTER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUMBER_AFTER" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.detail_receipt" Member="detail_receipts">
    <Type Name="detail_receipt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_RECEIPT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ITEM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_TABLE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMBER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="item_detail_receipt" Member="item" ThisKey="ID_ITEM" OtherKey="ID" Type="item" IsForeignKey="true" />
      <Association Name="receipt_detail_receipt" Member="receipt" ThisKey="ID_RECEIPT" OtherKey="ID" Type="receipt" IsForeignKey="true" />
      <Association Name="table_detail_receipt" Member="table" ThisKey="ID_ITEM" OtherKey="ID" Type="table" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.detail_receipt_import" Member="detail_receipt_imports">
    <Type Name="detail_receipt_import">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_RECEIPT_IMPORT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ITEM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMBER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="item_detail_receipt_import" Member="item" ThisKey="ID_ITEM" OtherKey="ID" Type="item" IsForeignKey="true" />
      <Association Name="receipt_import_detail_receipt_import" Member="receipt_import" ThisKey="ID_RECEIPT_IMPORT" OtherKey="ID" Type="receipt_import" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.grant_right" Member="grant_rights">
    <Type Name="grant_right">
      <Column Name="ID_GROUP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SCREEN" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROLE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="group_user_grant_right" Member="group_user" ThisKey="ID_GROUP" OtherKey="ID" Type="group_user" IsForeignKey="true" />
      <Association Name="screen_grant_right" Member="screen" ThisKey="ID_SCREEN" OtherKey="ID" Type="screen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.group_user" Member="group_users">
    <Type Name="group_user">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_GROUP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="group_user_user_group_user" Member="user_group_users" ThisKey="ID" OtherKey="ID_GROUP" Type="user_group_user" />
      <Association Name="group_user_grant_right" Member="grant_rights" ThisKey="ID" OtherKey="ID_GROUP" Type="grant_right" />
    </Type>
  </Table>
  <Table Name="dbo.inventory" Member="inventories">
    <Type Name="inventory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ITEM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="item_inventory" Member="item" ThisKey="ID_ITEM" OtherKey="ID" Type="item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_ITEM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRICE_SELL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRICE_PURCHASE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ID_TYPE_ITEM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NUMBER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="item_detail_receipt" Member="detail_receipts" ThisKey="ID" OtherKey="ID_ITEM" Type="detail_receipt" />
      <Association Name="item_detail_receipt_import" Member="detail_receipt_imports" ThisKey="ID" OtherKey="ID_ITEM" Type="detail_receipt_import" />
      <Association Name="item_inventory" Member="inventories" ThisKey="ID" OtherKey="ID_ITEM" Type="inventory" />
      <Association Name="type_item_item" Member="type_item" ThisKey="ID_TYPE_ITEM" OtherKey="ID" Type="type_item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.profile" Member="profiles">
    <Type Name="profile">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TYPE_CUSTOMER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFICATION" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LAST_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FIRST_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SEX" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="account_profile" Member="account" ThisKey="ID_ACCOUNT" OtherKey="ID" Type="account" IsForeignKey="true" />
      <Association Name="type_customer_profile" Member="type_customer" ThisKey="ID_TYPE_CUSTOMER" OtherKey="ID" Type="type_customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.profile_staff" Member="profile_staffs">
    <Type Name="profile_staff">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_TIMEKEEPING" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME_STAFF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="timekeeping_profile_staff" Member="timekeeping" ThisKey="ID_TIMEKEEPING" OtherKey="ID" Type="timekeeping" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.receipt" Member="receipts">
    <Type Name="receipt">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CODE_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_ACCOUNT_STAFF" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ACCOUNT_CUSTOMER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_AT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SUM_MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="receipt_detail_receipt" Member="detail_receipts" ThisKey="ID" OtherKey="ID_RECEIPT" Type="detail_receipt" />
      <Association Name="account_receipt" Member="account" ThisKey="ID_ACCOUNT_STAFF" OtherKey="ID" Type="account" IsForeignKey="true" />
      <Association Name="account_receipt1" Member="account1" ThisKey="ID_ACCOUNT_CUSTOMER" OtherKey="ID" Type="account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.receipt_import" Member="receipt_imports">
    <Type Name="receipt_import">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CODE_IMPORT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_SUPPLIER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ACCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATE_AT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SUM_MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="receipt_import_detail_receipt_import" Member="detail_receipt_imports" ThisKey="ID" OtherKey="ID_RECEIPT_IMPORT" Type="detail_receipt_import" />
      <Association Name="account_receipt_import" Member="account" ThisKey="ID_ACCOUNT" OtherKey="ID" Type="account" IsForeignKey="true" />
      <Association Name="supplier_receipt_import" Member="supplier" ThisKey="ID_SUPPLIER" OtherKey="ID" Type="supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.screen" Member="screens">
    <Type Name="screen">
      <Column Name="ID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_SCREEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="screen_grant_right" Member="grant_rights" ThisKey="ID" OtherKey="ID_SCREEN" Type="grant_right" />
    </Type>
  </Table>
  <Table Name="dbo.supplier" Member="suppliers">
    <Type Name="supplier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="supplier_receipt_import" Member="receipt_imports" ThisKey="ID" OtherKey="ID_SUPPLIER" Type="receipt_import" />
    </Type>
  </Table>
  <Table Name="dbo.[table]" Member="tables">
    <Type Name="table">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_AREA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME_TABLE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="table_detail_receipt" Member="detail_receipts" ThisKey="ID" OtherKey="ID_ITEM" Type="detail_receipt" />
      <Association Name="area_table" Member="area" ThisKey="ID_AREA" OtherKey="ID" Type="area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.thuchi" Member="thuchis">
    <Type Name="thuchi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="REASON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MONEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="account_thuchi" Member="account" ThisKey="ID_ACCOUNT" OtherKey="ID" Type="account" IsForeignKey="true" />
      <Association Name="type_ballot_thuchi" Member="type_ballot" ThisKey="ID_TYPE" OtherKey="ID" Type="type_ballot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.timekeeping" Member="timekeepings">
    <Type Name="timekeeping">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SHIFT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="timekeeping_profile_staff" Member="profile_staffs" ThisKey="ID" OtherKey="ID_TIMEKEEPING" Type="profile_staff" />
      <Association Name="account_timekeeping" Member="account" ThisKey="ID_ACCOUNT" OtherKey="ID" Type="account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.type_ballot" Member="type_ballots">
    <Type Name="type_ballot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="type_ballot_thuchi" Member="thuchis" ThisKey="ID" OtherKey="ID_TYPE" Type="thuchi" />
    </Type>
  </Table>
  <Table Name="dbo.type_customer" Member="type_customers">
    <Type Name="type_customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="type_customer_profile" Member="profiles" ThisKey="ID" OtherKey="ID_TYPE_CUSTOMER" Type="profile" />
    </Type>
  </Table>
  <Table Name="dbo.type_item" Member="type_items">
    <Type Name="type_item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_TYPE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="type_item_item" Member="items" ThisKey="ID" OtherKey="ID_TYPE_ITEM" Type="item" />
    </Type>
  </Table>
</Database>